### ISSUE TITLE
Task failure reason is: Cannot generate CompilerPass from empty list.

### ISSUE THREAD

**Issue by epelofske-LANL** [aws/amazon-braket-sdk-python#348]
**Describe the bug**
I ran a circuit on the OQC Lucy backend, it returned an error `Task failure reason is: Cannot generate CompilerPass from empty list.` This error does not give enough details for me to know where the bug is at, but I think that the circuit is valid. 

**To reproduce**
I do not know what properties of the circuit triggered this error, here is a screenshot of it (I needed to add the identify gates in order to not trigger a non contiguous qubit error): 
<img width="954" alt="circ" src="https://user-images.githubusercontent.com/69176477/168554105-bfeabc8c-284f-44c9-bea0-0f98bb3f4fba.png">

**Expected behavior**
Output should look like this:

```
Task is in terminal state FAILED and no result is available.
Task failure reason is: Cannot generate CompilerPass from empty list.
```

**System information**
- **Amazon Braket Python SDK version**: `1.21.0`
- **Amazon Braket Python Schemas version**: `1.9.0`
- **Amazon Braket Python Default Simulator version**: `1.6.2` 
- **Python version**: `Python 3.9.7`

**Additional context**
I am guessing that the error comes from the identity gates being removed because they are redundant (which is fine, and intentional, but required in order to not trigger a pre-processing error in amazon-braket-sdk) and then a server side compiler attempting to handle empty qubit lines.

**Comment by epelofske-LANL** [comment]
I am still not sure what exactly the cause of this error is, but I have resolved it on my end by not using the identity gates. It appears that the local simulator was throwing errors when the qubit indices were not contiguous. However, when submitting to the OQC backend the task passes the validation step if the qubit indices are not contiguous.

**Comment by mbeach-aws** [comment]
Hi @epelofske-LANL

I believe the `Task failure reason is: Cannot generate CompilerPass from empty list.` error is from passing `disable_qubit_rewiring=True` as an argument to `device.run()`. Unfortunately, the OQC compiler does not allow us to disable qubit rewiring in general. We're rolling out a hotfix to make the error message more meaningful. 

Since the circuit you posted is composed of native gates, a possible workaround is to use verbatim circuits:
```python
verbatim_circuit = Circuit().add_verbatim_box(circuit)
device.run(verbatim_circuit, shots=10, disable_qubit_rewiring=True)
```
In this case `disable_qubit_rewiring` works as expected since the circuit is verbatim (which means the compiler doesn't touch the circuit and it's run directly as is)


As for the local simulator, yes, it currently only supports contiguous qubits whereas QPUs support non-contiguous qubits. A possible workaround is something like this, which  maps the circuit to a contiguous qubit circuit:
```python
def map_to_contiguous(circuit: Circuit) -> Circuit:
    """Maps a circuit into a circuit of contiguous qubits.

    Args:
        circuit (Circuit): Input circuit
    Returns:
        Circuit: Output circuit composed of contiguous qubits.
    """
    qubit_dict = {int(qubit): index for index, qubit in enumerate(sorted(circuit.qubits))}
    new_circuit = Circuit()
    for instr in circuit.instructions:
        if len(instr.target) == 1:
            new_circuit.add_instruction(
                Instruction(instr.operator, qubit_dict[int(instr.target[0])])
            )
        elif len(instr.target) == 2:
            qubit0, qubit1 = qubit_dict[int(instr.target[0])], qubit_dict[int(instr.target[1])]
            new_circuit.add_instruction(Instruction(instr.operator, [qubit0, qubit1]))
    for result_type in circuit.result_types:
        new_circuit.add_result_type(result_type)
    return new_circuit
```

Please let me know if those work for you.

**Comment by epelofske-LANL** [comment]
For the Local simulator, the contiguous qubit index remapping does work as expected. 
For verbatim compilation, it now works such that with a verbatim box `Circuit().add_verbatim_box(circuit)` the circuit optimizations are turned off for Lucy, whereas without a verbatim box circuit optimizations are turned on. I think this addresses the errors I was seeing; closing the issue.
