### ISSUE TITLE
Circuit's QASM output doesn't contain stdgates.inc include

### ISSUE THREAD

**Issue by rht** [aws/amazon-braket-sdk-python#452]
**Describe the bug**
Exactly as the title says.
```python
from braket.circuits import Circuit
from braket.circuits.serialization import IRType

bell = Circuit().h(0).cnot(0, 1)
qasm = bell.to_ir(IRType.OPENQASM)
print(qasm.source)
```
```
OPENQASM 3.0;
bit[2] b;
qubit[2] q;
h q[0];
cnot q[0], q[1];
b[0] = measure q[0];
b[1] = measure q[1];
```
This causes a problem for any arbitrary OQ3 parser, because stdgates.inc is not declared, which means the `h` and `cnot` are undefined gates.

**Expected behavior**
The QASM output should contain `include "stdgates.inc";`.

**Comment by ajberdy** [comment]
Hi, this is the expected behavior. Circuit gates are translated to built-in Braket gates, such as h and cnot, which are understood by Braket backends like the local and on-demand simulators. These built-in gates differ from the ones defined in stdgates.inc, with some names being changed and some differences in which gates are present. To work with an arbitrary OQ3 backend, you would need to supply an implementation of the Braket gates in OpenQASM. I am curious to hear more about your use case; feel free to reference [braket_gates.inc](https://github.com/aws/amazon-braket-default-simulator-python/blob/92186bd6445d322b5e2b4a553f0e0331f7715762/src/braket/default_simulator/openqasm/braket_gates.inc) to see some reference implementations of our built-in gates.

**Comment by rht** [comment]
I see, thank you for the pointer to braket_gates.inc. I'm just writing my own general OQ3 parser, and happened to encounter the gates include issue. Should I close this issue, or are you planning to add explicit `include "braket_gates.inc";` in the QASM output?

**Comment by ajberdy** [comment]
We don't currently have plans to add that include statement, since those gates are implicitly understood by all Braket backends. You should be able to create a translator function that takes a Braket Circuit OQ3 output and transforms it into a general form with the inclusion of the braket_gates.inc file. The [default simulator](https://github.com/aws/amazon-braket-default-simulator-python) oq3 implementation may be a useful resource to reference! Please let me know if you have any questions, otherwise feel free to close this issue

**Comment by rht** [comment]
I see, thank you for the pointer to the simulator. If I have more questions, I will create a separate issue instead.
